<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7872" started-at="2022-06-12T00:39:30Z" finished-at="2022-06-12T00:39:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7872" started-at="2022-06-12T00:39:30Z" finished-at="2022-06-12T00:39:38Z">
      <class name="findingelements.FindByElements">
        <test-method status="PASS" signature="opeURL()[pri:0, instance:findingelements.FindByElements@4df50bcc]" name="opeURL" is-config="true" duration-ms="7133" started-at="2022-06-12T01:39:30Z" finished-at="2022-06-12T01:39:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- opeURL -->
        <test-method status="FAIL" signature="testFindElements()[pri:0, instance:findingelements.FindByElements@4df50bcc]" name="testFindElements" duration-ms="57" started-at="2022-06-12T01:39:37Z" finished-at="2022-06-12T01:39:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [46] but found [41]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [46] but found [41]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:652)at org.testng.Assert.assertEquals(Assert.java:662)at findingelements.FindByElements.testFindElements(FindByElements.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindElements -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:findingelements.FindByElements@4df50bcc]" name="closeDriver" is-config="true" duration-ms="659" started-at="2022-06-12T01:39:37Z" finished-at="2022-06-12T01:39:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- findingelements.FindByElements -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
